server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/admin_read
    username: admin
    password: admin_pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: admin-service
      auto-offset-reset: earliest
    producer:
      acks: all
