apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway.yaml
  - queue-service.yaml
  - reservation-service.yaml
  - payment-service.yaml
  - user-service.yaml
  - front-deployment.yaml
  - front-service.yaml
  - redis.yaml
  - kafka.yaml
  - postgres.yaml
  - minio.yaml
commonLabels:
  app.kubernetes.io/part-of: ticketing
